= SASIL potential activities

== International Mother Language Day (IMLD)

International Mother Language Day (IMLD) is a worldwide annual
observance held on 21 February to promote awareness of linguistic
and cultural diversity and promote multilingualism.

* https://www.un.org/en/events/motherlanguageday/
* https://en.wikipedia.org/wiki/International_Mother_Language_Day



== Translation of the Universal Declaration of Linguistic Rights

See link:references/drets_culturals389.pdf[]


== Translation of the Girona Manifesto

See link:references/Girona-Manifesto-ENGLISH.pdf[]



== Translation of United Nations Convention on the Rights of the Child

The United Nations Convention on the Rights of the Child (commonly
abbreviated as the CRC or UNCRC) is a human rights treaty which
sets out the civil, political, economic, social, health and
cultural rights of children. The Convention defines a child as any
human being under the age of eighteen, unless the age of majority
is attained earlier under national legislation.


== Setting out individual linguistic rights

(From Wikipedia)

The most basic definition of linguistic rights is the right of
individuals to use their language with other members of their
linguistic group, regardless of the status of their language. They
evolve from general human rights, in particular:
non-discrimination, freedom of expression, right to private life,
and the right of members of a linguistic minority to use their
language with other members of their community.

Individual linguistic rights are provided for in the Universal
Declaration of Human Rights:

* Article 2 – all individuals are entitled to the rights declared
without discrimination based on language.
* Article 10 – individuals are entitled to a fair trial, and this
is generally recognized to involve the right to an interpreter if
an individual does not understand the language used in criminal
court proceedings, or in a criminal accusation. The individual has
the right to have the interpreter translate the proceedings,
including court documents.
* Article 19 – individuals have the right to freedom of expression,
including the right to choose any language as the medium of
expression.
* Article 26 – everyone has the right to education, with relevance
to the language of medium of instruction.

Linguistic rights can be applied to the private arena and the
public domain.

