= Articles of the Standardization association of Sinitic Languages and Han Characters
2021-02-25

== General

=== Name

The name of the association is "Standardization association of Sinitic Languages and Han Characters" in English,  漢語漢字標準協會 in Chinese.

=== Status

The association is established as a Verein in the Canton of Zürich, Switzerland.

=== Non-profit making

The association is a non-profit-making, non-governmental, international, standardization organization.

=== Purpose

The association is an international standardization organization for matters relating to Sinitic languages and languages that utilize Sinographic or its derived characters.

Its mission includes:

* facilitate teaching and daily use of these languages
* development and publication of international standards in the application and usage of the subject matter.
* promotion of standards and research of the subject matter
* research and modern academic and technical research
* promote the sustainable long-term development of the language infrastructure

////
Covers multiple languages, scripts, spoken form, spellings, modern and historic,

The association is committed to the modernization of the application standards of the Chinese language, including modern standard Chinese, Chinese dialects, ancient Chinese, dialects, etc. And the research of technical theory, so that Chinese language can achieve the goal of optimization in

in order to facilitate teaching, daily use, especially the application of network technology, and finally
////

=== Organizational structure

The association is run by its Board of Directors.

=== Work

. Organize various working groups on the modernization of Chinese language standards to discuss and promote cooperation and exchanges between scholars, industries, governments and international standards organizations from all over the world;
. publication and editing of the association website;
. Organizing a working group to conduct research and discussion;
. Publishing related academic works;  
. Raise scientific research funds, organize research and development academic and technical projects;
. Organize seminars and conferences to popularize the modern concept of language standards; train research teams to engage in this work.


== Membership

=== Membership

Those who are interested in the academic and technical research and international and domestic promotion of the modern Chinese language standard or are engaged in related workers and organizations, and can abide by the constitution of the society and pay the dues on time, then they can become members of the association or institutional members.


=== Enrollment and withdrawal procedures

. Applicants shall submit a formal application, which will be accepted after the committee's review and approval;
. Voluntary withdrawal: the member himself should submit a written report, file it with the association committee and notify all members;
. Suspension of membership: Those who seriously violate the constitution of the association shall be discussed and decided by the committee and announced in an appropriate manner, and the membership will be cancelled.

=== Member Categories

The members of this association are divided into basic members, associate members and group members.

Honorary members are established in accordance with the needs of the society for academic research activities, and after the committee has discussed and approved them, they will be awarded honorary presidents, honorary members, consultants, etc.;
. Associate members have no right to vote, to be elected and to vote, and the membership fee is one-half of ordinary members.
. Group members must be corporate legal persons, and membership fees and permanent membership fees are ten times that of ordinary members.

=== Member Rights

. Only basic members have the right to vote, to be elected and to vote;  
. Participate in the activities of the association;
. Get the priority of the service of the association;
. Deduction of the work of the association: right to comment and suggest and supervise;
. Have the right to withdraw freely.

=== Member Obligations

. Implement the resolutions of the association;
. Maintain the legal rights and reputation of the association;
. Pay the dues on time according to the standards set by the association.

=== Lifetime membership

Ordinary members who pay ten-year membership fees at a time can become life-long members and do not need to pay membership fees in the future.

=== Withdrawal

Members who withdraw from the membership should notify the secretariat of the Society in writing. Members who fail to pay dues or participate in the activities of the Society for two consecutive years will be deemed to have withdrawn automatically.



== General meeting

=== General assembly

The general assembly is held once a year.

If more than two-thirds of the members propose to convene
A special membership meeting in advance. The board of directors and advisory committee members are elected every four years. The general meeting is chaired by the board of directors. The agenda of the general meeting must be published by (electronic) communication two weeks before the meeting.

=== Permission of the General Assembly

. Modify the association's constitution;
. Elect the committee of the association;
. Discuss and resolve other issues of the association. 


== Board of directors

=== Membership

The committee consists of more than XX members. Members are elected by the general assembly and require more than half of the valid votes to be elected. Members can vote by correspondence or entrust other members to vote in writing.

=== Leadership

The association has one president and two vice presidents. The president presides over the work of the association; the vice president assists the president in work.

=== Terms

Each member of the board of director serves a term of four years, and they can be re-elected upon expiration and can serve two consecutive terms.

=== Permissions and duties of directors of the board

. Attend board meetings, participate in discussions and decide important matters of the association;
. Election of president and vice president;
. Co-lead and manage the activities of the association;
. Listen to, discuss and approve the president's annual work report;
. To implement the resolutions of the General Assembly;
. Report the work of the association and annual financial accounts to the general assembly;
. Hire consultants;
. Accept and expel members.
