= SASIL potential external parties

== SIL

https://www.sil.org/international-relations

== UN ECOSOC

* ECOSOC Consultative Status
** https://www.un.org/development/desa/dspd/civil-society/ecosoc-status.html
** https://en.unesco.org/partnerships/non-governmental-organizations

== Asia Society

https://asiasociety.org/china-learning-initiatives/organizations-supporting-language-learning

== The Consortium for Language Teaching and Learning

http://languageconsortium.org

The Consortium for Language Teaching and Learning is an association
of six institutions of higher education (the University of Chicago,
Columbia University, Cornell University, Brown University,
Princeton University and Yale University) established in 1986 and
dedicated to the study and instruction of second languages at the
post-secondary level.

== American Association For Applied Linguistics

https://www.aaal.org

Founded in 1977, the American Association for Applied Linguistics
(AAAL) is a professional organization of scholars who are
interested in and actively contribute to the multi-disciplinary
field of applied linguistics. AAAL members promote principled
approaches to language-related concerns, including language
education, acquisition and loss, bilingualism, discourse analysis,
literacy, rhetoric and stylistics, language for special purposes,
psycholinguistics, second and foreign language pedagogy, language
assessment, and language policy and planning.

Organizationally, AAAL is the United States affiliate of the
International Association of Applied Linguistics (Association
Internationale de Linguistique Appliquée, AILA).



== AILA

https://aila.info

AILA is the acronym for Association Internationale de Linguistique
Appliquée or International Association of Applied Linguistics. AILA
(originally founded in 1964 in France) is an international
federation of national and regional associations of Applied
Linguistics. AILA has a membership of more than 8.000 individuals
worldwide who as researchers, policy makers or practitioners are
active in the field of Applied Linguistics.


== Modern Language Association

https://www.mla.org

Founded in 1883, the Modern Language Association of America has
worked for more than a century to strengthen the study and teaching
of languages and literatures.


== The Chinese Language Teachers Association, USA

http://clta-us.org

The Chinese Language Teachers Association, USA, Inc. (CLTA) is a
professional organization devoted exclusively to the study of
Chinese language, culture and pedagogy. (See our Mission
Statement.) In the years since our establishment in 1962, the
Chinese Language Teachers Association has both reflected and
responded to changes in our students, our teachers and our world.
Although approximately half of our membership is composed of
specialists in Chinese language, literature, linguistics and
culture teaching at colleges and universities throughout the world,
we increasingly count among our membership teachers of Chinese at
primary and secondary schools and Chinese community schools, as
well as students of the language and other interested parties. From
each of these diverse types of experts, we learn much, and can
consequently give much more to all of us engaged in the learning
and teaching of the Chinese language.


== Confucius Institute of Hong Kong

https://cihk.org.hk

Under the auspices of The Hong Kong Polytechnic University (PolyU)
and Hanban, the Confucius Institute of Hong Kong (CIHK) was
inaugurated in 2006, dedicated to the promotion of Chinese language
and culture as well as the facilitation of cultural exchanges
between China and the world. As the only Confucius Institute in the
territory and the only one of its kind in China, CIHK addresses
Hong Kong’s unique historical background and socio-economic
conditions and provides various types of activities and programmes
for local residents to broaden and deepen their understanding of
Chinese history and traditional culture as well as that of
contemporary China.


== Linguistic Society of America

https://www.linguisticsociety.org

The Linguistic Society of America (LSA) was founded in 1924 to
advance the scientific study of language. LSA plays a critical role
in supporting and disseminating linguistic scholarship both to
professional linguists and to the general public.


== Center for Applied Linguistics

http://www.cal.org

The Center for Applied Linguistics is a nonprofit organization
promoting access, equity and
mutual understanding
for linguistically and culturally diverse people around the world.


== American Council on the Teaching of Foreign Languages

https://www.actfl.org

The American Council on the Teaching of Foreign Languages (ACTFL)
is dedicated to the improvement and expansion of the teaching and
learning of all languages at all levels of instruction. ACTFL is an
individual membership organization of more than 12,500 language
educators and administrators from elementary through graduate
education, as well as government and industry.

Since its founding (in 1967), ACTFL has become synonymous with
innovation, quality, and reliability in meeting the changing needs
of language educators and their students. From the development of
Proficiency Guidelines, to its leadership role in the creation of
national standards, ACTFL focuses on issues that are critical to
the growth of both the profession and the individual teacher.
